_currencies = \
    {
        'USD': 'United States Dollar',
        'EUR': 'Euro',
        'GBP': 'British Pound Sterling',
        'INR': 'Indian Rupee',
        'AUD': 'Australian Dollar',
        'CAD': 'Canadian Dollar',
        'ZAR': 'South African Rand',
        'NZD': 'New Zealand Dollar',
        'JPY': 'Japanese Yen',
        'SGD': 'Singapore Dollar',
        'CNY': 'Chinese Yuan',
        'CHF': 'Swiss Franc',
        'MYR': 'Malaysian Ringgit',
        'HUF': 'Hungarian Forint',
        'HKD': 'Hong Kong Dollar',
        'AED': 'United Arab Emirates Dirham',
        'THB': 'Thai Baht',
        'KRW': 'South Korean Won',
        'SEK': 'Swedish Krona',
        'PHP': 'Philippine Peso',
        'ILS': 'Israeli New Sheqel',
        'TRY': 'Turkish Lira',
        'PLN': 'Polish Zloty',
        'MXN': 'Mexican Peso',
        'NOK': 'Norwegian Krone',
        'DKK': 'Danish Krone',
        'KWD': 'Kuwaiti Dinar',
        'BRL': 'Brazilian Real',
        'IDR': 'Indonesian Rupiah',
        'TWD': 'New Taiwan Dollar',
        'SAR': 'Saudi Riyal',
        'PKR': 'Pakistani Rupee',
        'CZK': 'Czech Republic Koruna',
        'IQD': 'Iraqi Dinar',
        'RUB': 'Russian Ruble',
        'KES': 'Kenyan Shilling',
        'JOD': 'Jordanian Dinar',
        'CLP': 'Chilean Peso',
        'ARS': 'Argentine Peso',
        'EGP': 'Egyptian Pound',
        'VND': 'Vietnamese Dong',
        'QAR': 'Qatari Rial',
        'XAU': 'Gold (troy ounce)',
        'RON': 'Romanian Leu',
        'COP': 'Colombian Peso',
        'OMR': 'Omani Rial',
        'BGN': 'Bulgarian Lev',
        'XAG': 'Silver (troy ounce)',
        'TND': 'Tunisian Dinar',
        'MAD': 'Moroccan Dirham',
        'BHD': 'Bahraini Dinar',
        'ISK': 'Icelandic Króna',
        'LKR': 'Sri Lankan Rupee',
        'HRK': 'Croatian Kuna',
        'GEL': 'Georgian Lari',
        'UAH': 'Ukrainian Hryvnia',
        'IRR': 'Iranian Rial',
        'NGN': 'Nigerian Naira',
        'XAF': 'CFA Franc BEAC',
        'LVL': 'Latvian Lats',
        'LTL': 'Lithuanian Litas',
        'BDT': 'Bangladeshi Taka',
        'MUR': 'Mauritian Rupee',
        'ALL': 'Albanian Lek',
        'FJD': 'Fijian Dollar',
        'PEN': 'Peruvian Nuevo Sol',
        'XOF': 'CFA Franc BCEAO',
        'BOB': 'Bolivian Boliviano',
        'BYR': 'Belarusian Ruble',
        'UYU': 'Uruguayan Peso',
        'BAM': 'Bosnia-Herzegovina Convertible Mark',
        'UZS': 'Uzbekistan Som',
        'KZT': 'Kazakhstani Tenge',
        'MKD': 'Macedonian Denar',
        'MDL': 'Moldovan Leu',
        'AMD': 'Armenian Dram',
        'KGS': 'Kyrgystani Som',
        'TJS': 'Tajikistani Somoni',
        'TMT': 'Turkmenistani Manat',
        'VEF': 'Venezuelan Bolívar Fuerte',
        'DOP': 'Dominican Peso',
        'JMD': 'Jamaican Dollar',
        'DZD': 'Algerian Dinar',
        'XPF': 'CFP Franc',
        'UGX': 'Ugandan Shilling',
        'CRC': 'Costa Rican Colón',
        'ZMK': 'Zambian Kwacha (pre-2013)',
        'BND': 'Brunei Dollar',
        'LYD': 'Libyan Dinar',
        'XCD': 'East Caribbean Dollar',
        'BBD': 'Barbadian Dollar',
        'TTD': 'Trinidad and Tobago Dollar',
        'LBP': 'Lebanese Pound',
        'SYP': 'Syrian Pound',
        'KHR': 'Cambodian Riel',
        'NPR': 'Nepalese Rupee',
        'GTQ': 'Guatemalan Quetzal',
        'MOP': 'Macanese Pataca',
        'PYG': 'Paraguayan Guarani',
        'BWP': 'Botswanan Pula',
        'TZS': 'Tanzanian Shilling',
        'ANG': 'Netherlands Antillean Guilder',
        'BSD': 'Bahamian Dollar',
        'HNL': 'Honduran Lempira',
        'NAD': 'Namibian Dollar',
        'ETB': 'Ethiopian Birr',
        'ZWL': 'Zimbabwean Dollar',
        'BMD': 'Bermudan Dollar',
        'CUP': 'Cuban Peso',
        'NIO': 'Nicaraguan Córdoba',
        'MWK': 'Malawian Kwacha',
        'PAB': 'Panamanian Balboa',
        'VUV': 'Vanuatu Vatu',
        'HTG': 'Haitian Gourde',
        'XDR': 'Special Drawing Rights',
        'GYD': 'Guyanaese Dollar',
        'PGK': 'Papua New Guinean Kina',
        'WST': 'Samoan Tala',
        'LAK': 'Laotian Kip',
        'BZD': 'Belize Dollar',
        'YER': 'Yemeni Rial',
        'GMD': 'Gambian Dalasi',
        'KYD': 'Cayman Islands Dollar',
        'MNT': 'Mongolian Tugrik',
        'KPW': 'North Korean Won',
        'SVC': 'Salvadoran Colón',
        'SDG': 'Sudanese Pound',
        'MGA': 'Malagasy Ariary',
        'FKP': 'Falkland Islands Pound',
        'CVE': 'Cape Verdean Escudo',
        'AOA': 'Angolan Kwanza',
        'SCR': 'Seychellois Rupee',
        'MMK': 'Myanma Kyat',
        'GNF': 'Guinean Franc',
        'SLL': 'Sierra Leonean Leone',
        'AWG': 'Aruban Florin',
        'MVR': 'Maldivian Rufiyaa',
        'RWF': 'Rwandan Franc',
        'SBD': 'Solomon Islands Dollar',
        'TOP': 'Tongan Pa\'anga',
        'GIP': 'Gibraltar Pound',
        'DJF': 'Djiboutian Franc',
        'SOS': 'Somali Shilling',
        'LRD': 'Liberian Dollar',
        'MRO': 'Mauritanian Ouguiya',
        'BIF': 'Burundian Franc',
        'GHS': 'Ghanaian Cedi',
        'BTN': 'Bhutanese Ngultrum',
        'SRD': 'Surinamese Dollar',
        'SZL': 'Swazi Lilangeni',
        'LSL': 'Lesotho Loti',
        'SHP': 'Saint Helena Pound',
        'KMF': 'Comorian Franc',
        'STD': 'São Tomé and Príncipe Dobr',
        'ERN': 'Eritrean Nakfa',
        'MZN': 'Mozambican Metical',
        'AZN': 'Azerbaijani Manat',
        'AFN': 'Afghan Afghani',
        'BTC': 'Bitcoin',
        'BYN': 'New Belarusian Ruble',
        'CDF': 'Congolese Franc',
        'CLF': 'Chilean Unit of Account (UF)',
        'CUC': 'Cuban Convertible Peso',
        'GGP': 'Guernsey Pound',
        'IMP': 'Manx pound',
        'JEP': 'Jersey Pound',
        'RSD': 'Serbian Dinar',
        'ZMW': 'Zambian Kwacha'
    }
